name: bookshelfapp
description: Un pequeño proyecto el cual consiste en la realizacion de una aplicacion para busqueda y calificacion de libros.
publish_to: "none"
version: 0.0.5

environment:
  sdk: ">=3.1.0-171.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  http: ^1.0.0
  provider: ^6.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald/Oswald-Light.ttf
          weight: 300
        - asset: fonts/Oswald/Oswald-Regular.ttf
          weight: 400
        - asset: fonts/Oswald/Oswald-Medium.ttf
          weight: 500
        - asset: fonts/Oswald/Oswald-SemiBold.ttf
          weight: 600
        - asset: fonts/Oswald/Oswald-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
